# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addlocal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDialog(object):
    def setupUi(self, AddDialog):
        AddDialog.setObjectName("AddDialog")
        AddDialog.resize(389, 126)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/187904-folders/png/folders-35.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddDialog.setWindowIcon(icon)
        AddDialog.setStyleSheet("background-color: rgb(194, 195, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(AddDialog)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.openfiledialog = QtWidgets.QToolButton(AddDialog)
        self.openfiledialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.openfiledialog.setObjectName("openfiledialog")
        self.horizontalLayout.addWidget(self.openfiledialog)
        self.import_2 = QtWidgets.QPushButton(AddDialog)
        self.import_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_2.setObjectName("import_2")
        self.horizontalLayout.addWidget(self.import_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddDialog)
        QtCore.QMetaObject.connectSlotsByName(AddDialog)

    def retranslateUi(self, AddDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDialog.setWindowTitle(_translate("AddDialog", "Add from local"))
        self.label.setText(_translate("AddDialog", "File directory"))
        self.openfiledialog.setToolTip(_translate("AddDialog", "File dialog"))
        self.openfiledialog.setText(_translate("AddDialog", "..."))
        self.import_2.setToolTip(_translate("AddDialog", "Import the selected file"))
        self.import_2.setText(_translate("AddDialog", "Import"))
