# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addlocal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDialog(object):
    def setupUi(self, AddDialog):
        AddDialog.setObjectName("AddDialog")
        AddDialog.resize(351, 229)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/187904-folders/png/folders-35.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddDialog.setWindowIcon(icon)
        AddDialog.setStyleSheet("background-color: rgb(194, 195, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(AddDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(AddDialog)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.openfiledialog = QtWidgets.QToolButton(AddDialog)
        self.openfiledialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.openfiledialog.setObjectName("openfiledialog")
        self.horizontalLayout.addWidget(self.openfiledialog)
        self.import_2 = QtWidgets.QPushButton(AddDialog)
        self.import_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_2.setObjectName("import_2")
        self.horizontalLayout.addWidget(self.import_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(AddDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(AddDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.enterdoi = QtWidgets.QLineEdit(AddDialog)
        self.enterdoi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.enterdoi.setObjectName("enterdoi")
        self.horizontalLayout_2.addWidget(self.enterdoi)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(AddDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_3 = QtWidgets.QLabel(AddDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.typemanually = QtWidgets.QPushButton(AddDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.typemanually.sizePolicy().hasHeightForWidth())
        self.typemanually.setSizePolicy(sizePolicy)
        self.typemanually.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.typemanually.setObjectName("typemanually")
        self.horizontalLayout_3.addWidget(self.typemanually)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(AddDialog)
        QtCore.QMetaObject.connectSlotsByName(AddDialog)

    def retranslateUi(self, AddDialog):
        _translate = QtCore.QCoreApplication.translate
        AddDialog.setWindowTitle(_translate("AddDialog", "Add from local"))
        self.label.setText(_translate("AddDialog", "File directory"))
        self.openfiledialog.setToolTip(_translate("AddDialog", "File dialog"))
        self.openfiledialog.setText(_translate("AddDialog", "..."))
        self.import_2.setToolTip(_translate("AddDialog", "Import the selected file"))
        self.import_2.setText(_translate("AddDialog", "Import"))
        self.label_2.setText(_translate("AddDialog", "Enter DOI"))
        self.enterdoi.setPlaceholderText(_translate("AddDialog", "Enter DOI"))
        self.label_3.setText(_translate("AddDialog", "                                                    OR"))
        self.typemanually.setToolTip(_translate("AddDialog", "Use this only if you dont find DOI"))
        self.typemanually.setText(_translate("AddDialog", "Type Manually"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddDialog = QtWidgets.QDialog()
    ui = Ui_AddDialog()
    ui.setupUi(AddDialog)
    AddDialog.show()
    sys.exit(app.exec_())
