# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createfolder.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_d(object):
    def setupUi(self, Dialog_d):
        Dialog_d.setObjectName("Dialog_d")
        Dialog_d.resize(321, 150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_d.sizePolicy().hasHeightForWidth())
        Dialog_d.setSizePolicy(sizePolicy)
        Dialog_d.setMaximumSize(QtCore.QSize(321, 150))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/187904-folders/png/folders-17.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_d.setWindowIcon(icon)
        Dialog_d.setStyleSheet("background-color: rgb(194, 195, 255);")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_d)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog_d)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 30, 271, 60))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pastedoi = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.pastedoi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pastedoi.setObjectName("pastedoi")
        self.horizontalLayout.addWidget(self.pastedoi)
        self.getdoi = QtWidgets.QPushButton(Dialog_d)
        self.getdoi.setGeometry(QtCore.QRect(120, 90, 75, 23))
        self.getdoi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.getdoi.setObjectName("getdoi")

        self.retranslateUi(Dialog_d)
        self.buttonBox.accepted.connect(Dialog_d.accept)
        self.buttonBox.rejected.connect(Dialog_d.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_d)

    def retranslateUi(self, Dialog_d):
        _translate = QtCore.QCoreApplication.translate
        Dialog_d.setWindowTitle(_translate("Dialog_d", "Create folder"))
        self.label.setText(_translate("Dialog_d", "Enter DOI"))
        self.pastedoi.setPlaceholderText(_translate("Dialog_d", "Paste the DOI of the Article"))
        self.getdoi.setToolTip(_translate("Dialog_d", "Click to download and import"))
        self.getdoi.setText(_translate("Dialog_d", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_d = QtWidgets.QDialog()
    ui = Ui_Dialog_d()
    ui.setupUi(Dialog_d)
    Dialog_d.show()
    sys.exit(app.exec_())
