# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trial.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrialD(object):
    def setupUi(self, TrialD):
        TrialD.setObjectName("TrialD")
        TrialD.resize(314, 170)
        self.label = QtWidgets.QLabel(TrialD)
        self.label.setGeometry(QtCore.QRect(120, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.starttrial = QtWidgets.QPushButton(TrialD)
        self.starttrial.setGeometry(QtCore.QRect(120, 90, 75, 23))
        self.starttrial.setObjectName("starttrial")
        self.label_2 = QtWidgets.QLabel(TrialD)
        self.label_2.setGeometry(QtCore.QRect(0, 150, 241, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(TrialD)
        QtCore.QMetaObject.connectSlotsByName(TrialD)

    def retranslateUi(self, TrialD):
        _translate = QtCore.QCoreApplication.translate
        TrialD.setWindowTitle(_translate("TrialD", "Dialog"))
        self.label.setText(_translate("TrialD", "SciX Test Run"))
        self.starttrial.setText(_translate("TrialD", "Start trial"))
        self.label_2.setText(_translate("TrialD", "*requires internet to start your 15 days trial"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TrialD = QtWidgets.QDialog()
    ui = Ui_TrialD()
    ui.setupUi(TrialD)
    TrialD.show()
    sys.exit(app.exec_())
